---
build:
  test:
    image: golang:1.8-alpine
    commands:
      - apk -qq --no-cache add git
      - go get github.com/golang/dep/cmd/dep
      - go get github.com/golang/lint/golint
      - dep ensure -v
      - golint -set_exit_status $(go list ./... | grep -v vendor)
      - go test -v $(go list ./... | grep -v vendor)
      - go build -o captions-api
    when:
      event:
        - push
        - pull_request

publish:
  gcr:
    storage_driver: overlay

    registry: us.gcr.io
    repo: nyt-video-dev/video-captions-api
    tag:
      - latest
      - $$COMMIT
    token: >
      $$GOOGLE_CREDENTIALS_STG

    when:
      branch: master
      event: push

deploy:
  gke-stg:
    # Documentation: https://github.com/NYTimes/drone-gke/blob/master/DOCS.md.
    image: nytimes/drone-gke

    # For debugging
    dry_run:  false
    verbose: true

    zone: us-central1-b
    cluster: dev-cluster
    token: >
      $$GOOGLE_CREDENTIALS_STG

    # These variables are made available in the .kube.yml template.
    vars:
      image: us.gcr.io/nyt-video-dev/video-captions-api:$$COMMIT
      app: video-captions-api
      env: stg
      project_id: 'nyt-video-dev'
      bucket_name: 'video-captions-api-dev'
      port: 8000
      ce_esp_port: 8001
      ce_service_name: video-captions-api.endpoints.nyt-video-dev.cloud.goog
      ce_service_version: 2017-10-16r1
      replicas: 2
      # NOTE: recommend minimum of 2 to ensure uptime during a rolling deploy.
      replicas_min: 2
      replicas_max: 5
      cpu: 80
      ip_name: video-captions-api
      cert_name: stg-nyt-net-cert
      amara_team: nyt-cms

    # These variables are made available in the .kube.sec.yml secret template in base64 encoding.
    secrets:
      three_play_api_key: $$THREE_PLAY_API_KEY_STG
      three_play_api_secret: $$THREE_PLAY_API_SECRET_STG
      amara_token: $$AMARA_TOKEN
      amara_username: $$AMARA_USERNAME

    when:
      branch: master
      event: push

  gke-prd:
    image: nytimes/drone-gke

    # For debugging
    dry_run: false
    verbose: true

    zone: us-central1-b
    cluster: prd-cluster
    token: >
      $$GOOGLE_CREDENTIALS_PRD

    # These variables are made available in the .kube.yml template.
    vars:
      image: us.gcr.io/nyt-video-dev/video-captions-api:$$COMMIT
      app: video-captions-api
      env: prd
      project_id: 'nyt-video-prd'
      bucket_name: 'video-captions-api-prd'
      replicas: 5
      # NOTE: recommend minimum of 2 to ensure uptime during a rolling deploy.
      replicas_min: 3
      replicas_max: 10
      cpu: 80
      port: 8000
      ce_esp_port: 8001
      ce_service_name: video-captions-api.endpoints.nyt-video-prd.cloud.goog
      ce_service_version: 2017-10-16r1
      ip_name: video-captions-api
      cert_name: star-nyt-net-cert
      amara_team: nyt-cms

    secrets:
      three_play_api_key: $$THREE_PLAY_API_KEY_PRD
      three_play_api_secret: $$THREE_PLAY_API_SECRET_PRD
      amara_token: $$AMARA_TOKEN
      amara_username: $$AMARA_USERNAME

    when:
      event: tag


notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: media-factory

    when:
      event:
        - pull_request
        - push
        - tag
