---
build:
  test:
    image: golang:1.8-alpine
    commands:
      - apk update && apk add git mercurial bzr
      - go get
      - go build -o captions-api
    when:
      branch: master
      event: push

publish:
  gcr:
    storage_driver: overlay

    registry: us.gcr.io
    repo: nyt-video-dev/video-captions-api
    tag:
      - latest
      - $$COMMIT
    token: >
      $$GOOGLE_CREDENTIALS_DEV

    when:
      branch: master
      event: push

deploy:
  gke-dev:
    # Documentation: https://github.com/NYTimes/drone-gke/blob/master/DOCS.md.
    image: nytimes/drone-gke

    # For debugging
    dry_run:  false
    verbose: true

    zone: us-central1-b
    cluster: dev-cluster
    token: >
      $$GOOGLE_CREDENTIALS_DEV

    # These variables are made available in the .kube.yml template.
    vars:
      image: us.gcr.io/nyt-video-dev/video-captions-api:$$COMMIT
      app: video-captions-api
      env: dev
      port: 8000
      ce_esp_port: 8001
      ce_service_name: video-captions-api.endpoints.nyt-video-dev.cloud.goog
      ce_service_version: 2017-05-31r0
      replicas: 3
      # NOTE: recommend minimum of 2 to ensure uptime during a rolling deploy.
      replicas_min: 2
      replicas_max: 5
      cpu: 80
      ip_name: video-captions-api
      cert_name: stg-nyt-net-cert

    # These variables are made available in the .kube.sec.yml secret template in base64 encoding.

    when:
      branch: master
      event: push

