language: go
sudo: false
go:
- 1.9.x
- tip
install:
- go get github.com/golang/lint/golint
script:
- golint -set_exit_status $(go list ./...)
- make coverage
after_success:
  - 'if [ "${JOB}" = "test" ]; then bash <(curl -s https://codecov.io/bash); fi'
notifications:
  email: false
