language: go
sudo: false
addons:
  apt:
    packages:
      - docker-ce
cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin
env:
  global:
    - GO_FOR_RELEASE=1.x
    - GO111MODULE=on
go:
  - 1.x
  - tip
install:
  - go mod download
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@master
script:
  - make run-lint coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis-scripts/docker.bash
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    script: travis-scripts/deploy.bash stg
    on:
      repo: NYTimes/video-captions-api
      branch: master
      go: 1.x
  - provider: script
    skip_cleanup: true
    script: travis-scripts/deploy.bash prd
    on:
      repo: NYTimes/video-captions-api
      tags: true
      go: 1.x
