language: go
sudo: required
addons:
  apt:
    packages:
    - docker-ce
env:
  global:
  - GO_FOR_RELEASE=1.9
go:
- 1.9.x
- tip
install:
- go get github.com/golang/lint/golint
script:
- golint -set_exit_status $(go list ./...)
- make coverage
after_success:
- bash <(curl -s https://codecov.io/bash)
- travis-scripts/docker.bash
notifications:
  email: false
deploy:
- provider: script
  script: travis-scripts/deploy.bash stg
  on:
    branch: master
- provider: script
  script: travis-scripts/deploy.bash prd
  on:
    tags: true
