language: go
sudo: false
addons:
  apt:
    packages:
      - docker-ce
cache:
  directories:
    - $GOPATH/pkg
env:
  global:
    - GO_FOR_RELEASE=1.x
    - GO111MODULE=on
    - CGO_ENABLED=0
go:
  - 1.x
  - tip
install:
  - export GOCACHE=$GOPATH/pkg/cache
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
  - go mod download
script:
  - make run-lint coverage
  - go build -o video-captions-api
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis-scripts/docker.bash
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    script: travis-scripts/deploy.bash stg
    on:
      repo: NYTimes/video-captions-api
      branch: master
      go: 1.x
  - provider: script
    skip_cleanup: true
    script: travis-scripts/deploy.bash prd
    on:
      repo: NYTimes/video-captions-api
      tags: true
      go: 1.x
