FROM golang:1.8-alpine

WORKDIR /go/src/github.com/NYTimes/video-captions-api

RUN apk -qq update && apk -qq add --no-cache git mercurial bzr && go get github.com/pilu/fresh && go get github.com/Masterminds/glide

ENV SERVER_HTTP_PORT 8000
ENV SERVER_GIZMO_HEALTH_CHECK_PATH /healthz

COPY . .

RUN glide install

RUN echo 'ignored: vendor' > /tmp/runner.conf

CMD fresh -c /tmp/runner.conf

EXPOSE 8000
