FROM golang:1.8-alpine

WORKDIR /go/src/github.com/NYTimes/video-captions-api

RUN apk -qq update && apk -qq add --no-cache git mercurial bzr && go get github.com/pilu/fresh

ENV SERVER_HTTP_PORT 8000
ENV SERVER_GIZMO_HEALTH_CHECK_PATH /healthz

COPY . .

RUN go get -t ./...

CMD fresh

EXPOSE 8000
