[[constraint]]
  branch = "master"
  name = "github.com/NYTimes/gziphandler"

[[constraint]]
  branch = "master"
  name = "github.com/NYTimes/threeplay"

[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[override]]
  branch = "master"
  name = "github.com/NYTimes/gizmo"

[[override]]
  branch = "master"
  name = "github.com/julienschmidt/httprouter"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true
