x-google-allow: all
swagger: "2.0"
info:
  title: "video-captions-api"
  version: "0.1.0"
host: "video-captions-api.endpoints.nyt-video-dev.cloud.goog"

paths:
  "/healthz":
    get:
      operationId: "healthcheck-get"
      responses:
        default:
          description: "healthcheck-response"
      security: []
  "/**":
    get:
      operationId: "wildcard-get"
      responses:
        default:
          description: "wildcard-response"
    post:
      operationId: "wildcard-post"
      responses:
        default:
          description: "wildcard-response"

security:
  - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
